data_paths:
  raw_data_dir: data/raw
  train_file: train.csv
  store_file: store.csv
  processed_file: data/processed/data.csv

data_transformation:
  input_data_path: data/processed/data.csv
  output_data_path: data/transformed/transformed_data.csv
