data_paths:
  raw_data_dir: data/raw
  train_file: train.csv
  predict_file: test.csv
  store_file: store.csv
  processed_merged_file: data/processed/merged_data.csv
  processed_train_file: data/processed/train_data.csv
  processed_val_file: data/processed/val_data.csv

data_transformation:
  input_train_path: data/processed/train_data.csv
  output_train_path: data/transformed/train_transformed_data.csv
  input_val_path: data/processed/val_data.csv
  output_val_path: data/transformed/val_transformed_data.csv
