name: CI pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout code the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check formatting with black
        run: black --check src/ tests/

      - name: Check code style with flake8
        run: flake8 src/ tests/

      - name: Check import order with isort
        run: isort --check-only src/ tests/
      
      - name: Check coverage
        run: |
          coverage run -m pytest
          coverage report -m

      - name: Run tests
        run: |
          pytest